"""Auto increment users key

Revision ID: 051410773146
Revises: 4b69a7e7cf9f
Create Date: 2023-11-21 05:02:38.293238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '051410773146'
down_revision: Union[str, None] = '4b69a7e7cf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'total_worked')
    op.drop_index('ix_user_user_id', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_user_id', 'user', ['user_id'], unique=False)
    op.add_column('shifts', sa.Column('total_worked', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
