"""Cascade delete for User shifts

Revision ID: 0a5eaec3502c
Revises: e79d9a39da4f
Create Date: 2023-11-25 03:49:59.000861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5eaec3502c'
down_revision: Union[str, None] = 'e79d9a39da4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
